---
output: 
  html_document
css: styles.css
runtime: shiny
---
  
# Land use changes {.tabset}
  
```{r setup, message = F, warning = F, results = 'hide', echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, echo = F, fig.path = 'figs/', dev.args = list(family = 'serif'), fig.path = 'figures/')

library(tidyverse)
library(forcats)
library(foreign)
library(reactable)
library(here)
library(networkD3)
library(shiny)

load(url("https://github.com/tbep-tech/hmpu-workflow/raw/master/data/acres.RData"))
load(url("https://github.com/tbep-tech/hmpu-workflow/raw/master/data/subtacres.RData"))
load(url("https://github.com/tbep-tech/hmpu-workflow/raw/master/data/chgdat.RData"))
load(url("https://github.com/tbep-tech/hmpu-workflow/raw/master/data/subtchgdat.RData"))
fluccs <- read.csv('https://github.com/tbep-tech/hmpu-workflow/raw/master/data/FLUCCShabsclass.csv', stringsAsFactors = F)

source('R/funcs.R')

# land use years
yrs1 <- unique(acres$name) %>% 
  sort %>% 
  .[1:(length(.) - 1)]

# subtidal years
yrs2 <- unique(subtacres$name) %>% 
  sort %>% 
  .[1:(length(.) - 1)]
 
# # style file
# styles <- readLines('https://raw.githubusercontent.com/tbep-tech/css-styling/master/styles.css')
# writeLines(styles, 'styles.css')
```

```{r reactives}
# trend table
trndtab1 <- reactive({
  
  # inputs
  yrsel1 <- input$yrsel1

  sums <- acres %>%
    spread(name, Acres, fill = NA) %>% 
    rename(chgyr = !!yrsel1) %>% 
    mutate(
      chg = `2017` -  chgyr,
      chgper = 100 * (`2017` - chgyr) / chgyr
    ) %>% 
    rename(val = HMPU_TARGETS)
  
  names(sums)[names(sums) == 'chgyr'] <- yrsel1

  out <- lngtrmtab_fun(sums, 'Category', yrsel = yrsel1, topyr = '2017')
  
  return(out)
  
})

# trend table
trndtab2 <- reactive({
  
  # inputs
  yrsel2 <- input$yrsel2

  sums <- subtacres %>%
    spread(name, Acres, fill = 0) %>% 
    rename(chgyr = !!yrsel2) %>% 
    mutate(
      chg = `2018` -  chgyr,
      chgper = 100 * (`2018` - chgyr) / chgyr
    ) %>% 
    rename(val = HMPU_TARGETS)
  
  names(sums)[names(sums) == 'chgyr'] <- yrsel2

  out <- lngtrmtab_fun(sums, 'Category', yrsel = yrsel2, topyr = '2018')
  
  return(out)
  
})

# change data by year pairs
chgdatpr <- reactive({
  
  # inputs
  yrsel1 <- input$yrsel1
  
  out <- chgdat %>% 
    filter(grepl(paste0('\\,\\s', yrsel1, '$'), source))
  
  return(out)
  
})

# subtidal change data by year pairs
subtchgdatpr <- reactive({
  
  # inputs
  yrsel2 <- input$yrsel2
  
  out <- subtchgdat %>% 
    filter(grepl(paste0('\\,\\s', yrsel2, '$'), source))
  
  return(out)
  
})

# change analysis plot
alluplo1 <- reactive({
  
  # inputs
  datin <- chgdatpr()

  out <- alluvout2(datin, fluccs)
  
  return(out)
  
})

# subtidal change analysis plot
alluplo2 <- reactive({
  
  # inputs
  datin <- subtchgdatpr()

  out <- alluvout2(datin, fluccs)
  
  return(out)
  
})

# change analysis table
cmptab1 <- reactive({
  
  # inputs
  datin <- chgdatpr()
  yrsel1 <- input$yrsel1
  
  out <- cmprctfun2(datin, fluccs, yrsel1, '2017')
  
  return(out)
  
})

# subtidal change analysis table
cmptab2 <- reactive({
  
  # inputs
  datin <- subtchgdatpr()
  yrsel2 <- input$yrsel2
  
  out <- cmprctfun2(datin, fluccs, yrsel2, '2018', subt = T)
  
  return(out)
  
})
```

## Supratidal, intertidal

```{r}
selectInput('yrsel1', 'Select year comparison', choices = yrs1, selected = yrs1[1])
```

##### `r renderText(input$yrsel1)` to 2017 change {.tabset .tabset-pills} 

###### Long-term trends

```{r}
output$trndtab1 <- renderReactable(trndtab1())
reactableOutput('trndtab1')
```

###### Change analysis plot 

```{r}
output$alluplo1 <- renderSankeyNetwork(alluplo1())
sankeyNetworkOutput('alluplo1', height = '900px')
```

###### Change analysis table

```{r}
output$cmptab1 <- renderReactable(cmptab1())
reactableOutput('cmptab1')
```

## Subtidal

```{r}
selectInput('yrsel2', 'Select year comparison', choices = yrs2, selected = yrs2[1])
```

##### `r renderText(input$yrsel2)` to 2018 change {.tabset .tabset-pills} 

###### Long-term trends

```{r}
output$trndtab2 <- renderReactable(trndtab2())
reactableOutput('trndtab2')
```

###### Change analysis plot

```{r}
output$alluplo2 <- renderSankeyNetwork(alluplo2())
sankeyNetworkOutput('alluplo2', height = '900px')
```

###### Change analysis table

```{r}
output$cmptab2 <- renderReactable(cmptab2())
reactableOutput('cmptab2')
```
